version: '3'
# Define services
services:
  postgres:
    image: postgres:13.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: monobank
      POSTGRES_PASSWORD: test
      POSTGRES_DB: monobank