export type Transaction = {
  id: string;
  monoId: string;
  time: Date;
  description: string;
  mcc: number;
  hold: boolean;
  amount: number;
  operationAmount: number;
  currencyCode: number;
  commissionRate: number;
  cashbackAmount: number;
  balance: number;
  comment: string;
  receiptId: string;
  counterEdrpou: string;
  counterIban: string;
  createdAt: string;
  createdAtEpoch: number;
};
